name: spec

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run all specs

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Run tests
        run: rake spec SPEC_OPTS="--format documentation"
